const dummyData = {
  exams: [
    {
      id: 1,
      heading: "Engineering Entrance Exam",
      post_date: "2024-01-15",
      total_vacancy: 150,
      brief_description: "An entrance exam for various engineering courses.",
      adv_no: "EE2024/01",
      application_fee_general: 500.0,
      application_fee_women: 250.0,
      application_fee_obc: 300.0,
      application_fee_st_sc: 200.0,
      starting_date_apply_online: "2024-02-01",
      last_date_apply: "2024-03-01",
      last_date_payment_fee: "2024-03-05",
      age_limit_minimum: 18,
      age_limit_maximum: 25,
      notification_link: "https://example.com/engineering-notify",
      apply_online_link: "https://example.com/engineering-apply",
      official_website_link: "https://example.com/engineering",
      admit_card: {
        title: "Engineering Entrance Admit Card",
        description: "Admit card for the Engineering Entrance Exam 2024.",
        download_link: "https://example.com/download-engineering-admit-card",
      },
      result: {
        title: "Engineering Entrance Exam Results",
        description: "Results for the Engineering Entrance Exam 2024.",
        results_link: "https://example.com/engineering-results",
      },
    },
    {
      id: 2,
      heading: "Medical Entrance Exam",
      post_date: "2024-02-10",
      total_vacancy: 200,
      brief_description: "An entrance exam for medical courses.",
      adv_no: "ME2024/02",
      application_fee_general: 600.0,
      application_fee_women: 300.0,
      application_fee_obc: 350.0,
      application_fee_st_sc: 250.0,
      starting_date_apply_online: "2024-03-01",
      last_date_apply: "2024-04-01",
      last_date_payment_fee: "2024-04-05",
      age_limit_minimum: 17,
      age_limit_maximum: 26,
      notification_link: "https://example.com/medical-notify",
      apply_online_link: "https://example.com/medical-apply",
      official_website_link: "https://example.com/medical",
      admit_card: null,
      result: {
        title: "Medical Entrance Exam Results",
        description: "Results for the Medical Entrance Exam 2024.",
        results_link: "https://example.com/medical-results",
      },
    },
    {
      id: 3,
      heading: "Law Entrance Exam",
      post_date: "2024-03-05",
      total_vacancy: 100,
      brief_description: "An entrance exam for law courses.",
      adv_no: "LE2024/03",
      application_fee_general: 400.0,
      application_fee_women: 200.0,
      application_fee_obc: 250.0,
      application_fee_st_sc: 150.0,
      starting_date_apply_online: "2024-04-01",
      last_date_apply: "2024-05-01",
      last_date_payment_fee: "2024-05-05",
      age_limit_minimum: 20,
      age_limit_maximum: 30,
      notification_link: "https://example.com/law-notify",
      apply_online_link: "https://example.com/law-apply",
      official_website_link: "https://example.com/law",
      admit_card: {
        title: "Law Entrance Admit Card",
        description: "Admit card for the Law Entrance Exam 2024.",
        download_link: "https://example.com/download-law-admit-card",
      },
      result: null,
    },
    {
      id: 4,
      heading: "Management Entrance Exam",
      post_date: "2024-04-10",
      total_vacancy: 120,
      brief_description: "An entrance exam for management courses.",
      adv_no: "ME2024/04",
      application_fee_general: 550.0,
      application_fee_women: 275.0,
      application_fee_obc: 320.0,
      application_fee_st_sc: 220.0,
      starting_date_apply_online: "2024-05-01",
      last_date_apply: "2024-06-01",
      last_date_payment_fee: "2024-06-05",
      age_limit_minimum: 21,
      age_limit_maximum: 28,
      notification_link: "https://example.com/management-notify",
      apply_online_link: "https://example.com/management-apply",
      official_website_link: "https://example.com/management",
      admit_card: null,
      result: {
        title: "Management Entrance Exam Results",
        description: "Results for the Management Entrance Exam 2024.",
        results_link: "https://example.com/management-results",
      },
    },
    {
      id: 5,
      heading: "Teaching Entrance Exam",
      post_date: "2024-05-15",
      total_vacancy: 80,
      brief_description: "An entrance exam for teaching courses.",
      adv_no: "TE2024/05",
      application_fee_general: 450.0,
      application_fee_women: 225.0,
      application_fee_obc: 270.0,
      application_fee_st_sc: 180.0,
      starting_date_apply_online: "2024-06-01",
      last_date_apply: "2024-07-01",
      last_date_payment_fee: "2024-07-05",
      age_limit_minimum: 22,
      age_limit_maximum: 35,
      notification_link: "https://example.com/teaching-notify",
      apply_online_link: "https://example.com/teaching-apply",
      official_website_link: "https://example.com/teaching",
      admit_card: {
        title: "Teaching Entrance Admit Card",
        description: "Admit card for the Teaching Entrance Exam 2024.",
        download_link: "https://example.com/download-teaching-admit-card",
      },
      result: null,
    },
    {
      id: 6,
      heading: "Nursing Entrance Exam",
      post_date: "2024-06-20",
      total_vacancy: 90,
      brief_description: "An entrance exam for nursing courses.",
      adv_no: "NE2024/06",
      application_fee_general: 500.0,
      application_fee_women: 250.0,
      application_fee_obc: 300.0,
      application_fee_st_sc: 200.0,
      starting_date_apply_online: "2024-07-01",
      last_date_apply: "2024-08-01",
      last_date_payment_fee: "2024-08-05",
      age_limit_minimum: 18,
      age_limit_maximum: 30,
      notification_link: "https://example.com/nursing-notify",
      apply_online_link: "https://example.com/nursing-apply",
      official_website_link: "https://example.com/nursing",
      admit_card: null,
      result: {
        title: "Nursing Entrance Exam Results",
        description: "Results for the Nursing Entrance Exam 2024.",
        results_link: "https://example.com/nursing-results",
      },
    },
    {
      id: 7,
      heading: "Pharmacy Entrance Exam",
      post_date: "2024-07-10",
      total_vacancy: 130,
      brief_description: "An entrance exam for pharmacy courses.",
      adv_no: "PE2024/07",
      application_fee_general: 520.0,
      application_fee_women: 260.0,
      application_fee_obc: 310.0,
      application_fee_st_sc: 210.0,
      starting_date_apply_online: "2024-08-01",
      last_date_apply: "2024-09-01",
      last_date_payment_fee: "2024-09-05",
      age_limit_minimum: 18,
      age_limit_maximum: 27,
      notification_link: "https://example.com/pharmacy-notify",
      apply_online_link: "https://example.com/pharmacy-apply",
      official_website_link: "https://example.com/pharmacy",
      admit_card: {
        title: "Pharmacy Entrance Admit Card",
        description: "Admit card for the Pharmacy Entrance Exam 2024.",
        download_link: "https://example.com/download-pharmacy-admit-card",
      },
      result: {
        title: "Pharmacy Entrance Exam Results",
        description: "Results for the Pharmacy Entrance Exam 2024.",
        results_link: "https://example.com/pharmacy-results",
      },
    },
    {
      id: 8,
      heading: "Agriculture Entrance Exam",
      post_date: "2024-08-15",
      total_vacancy: 160,
      brief_description: "An entrance exam for agriculture courses.",
      adv_no: "AE2024/08",
      application_fee_general: 480.0,
      application_fee_women: 240.0,
      application_fee_obc: 290.0,
      application_fee_st_sc: 200.0,
      starting_date_apply_online: "2024-09-01",
      last_date_apply: "2024-10-01",
      last_date_payment_fee: "2024-10-05",
      age_limit_minimum: 18,
      age_limit_maximum: 28,
      notification_link: "https://example.com/agriculture-notify",
      apply_online_link: "https://example.com/agriculture-apply",
      official_website_link: "https://example.com/agriculture",
      admit_card: null,
      result: {
        title: "Agriculture Entrance Exam Results",
        description: "Results for the Agriculture Entrance Exam 2024.",
        results_link: "https://example.com/agriculture-results",
      },
    },
    {
      id: 9,
      heading: "Architecture Entrance Exam",
      post_date: "2024-09-10",
      total_vacancy: 140,
      brief_description: "An entrance exam for architecture courses.",
      adv_no: "AE2024/09",
      application_fee_general: 550.0,
      application_fee_women: 275.0,
      application_fee_obc: 320.0,
      application_fee_st_sc: 220.0,
      starting_date_apply_online: "2024-10-01",
      last_date_apply: "2024-11-01",
      last_date_payment_fee: "2024-11-05",
      age_limit_minimum: 17,
      age_limit_maximum: 30,
      notification_link: "https://example.com/architecture-notify",
      apply_online_link: "https://example.com/architecture-apply",
      official_website_link: "https://example.com/architecture",
      admit_card: {
        title: "Architecture Entrance Admit Card",
        description: "Admit card for the Architecture Entrance Exam 2024.",
        download_link: "https://example.com/download-architecture-admit-card",
      },
      result: {
        title: "Architecture Entrance Exam Results",
        description: "Results for the Architecture Entrance Exam 2024.",
        results_link: "https://example.com/architecture-results",
      },
    },
    {
      id: 10,
      heading: "Civil Services Exam",
      post_date: "2024-10-05",
      total_vacancy: 200,
      brief_description: "An exam for civil services recruitment.",
      adv_no: "CSE2024/10",
      application_fee_general: 700.0,
      application_fee_women: 350.0,
      application_fee_obc: 400.0,
      application_fee_st_sc: 300.0,
      starting_date_apply_online: "2024-11-01",
      last_date_apply: "2024-12-01",
      last_date_payment_fee: "2024-12-05",
      age_limit_minimum: 21,
      age_limit_maximum: 32,
      notification_link: "https://example.com/civil-services-notify",
      apply_online_link: "https://example.com/civil-services-apply",
      official_website_link: "https://example.com/civil-services",
      admit_card: null,
      result: {
        title: "Civil Services Exam Results",
        description: "Results for the Civil Services Exam 2024.",
        results_link: "https://example.com/civil-services-results",
      },
    },
    {
      id: 11,
      heading: "Defence Services Exam",
      post_date: "2024-11-15",
      total_vacancy: 180,
      brief_description: "An exam for recruitment into defence services.",
      adv_no: "DSE2024/11",
      application_fee_general: 600.0,
      application_fee_women: 300.0,
      application_fee_obc: 350.0,
      application_fee_st_sc: 250.0,
      starting_date_apply_online: "2024-12-01",
      last_date_apply: "2025-01-01",
      last_date_payment_fee: "2025-01-05",
      age_limit_minimum: 18,
      age_limit_maximum: 28,
      notification_link: "https://example.com/defence-services-notify",
      apply_online_link: "https://example.com/defence-services-apply",
      official_website_link: "https://example.com/defence-services",
      admit_card: {
        title: "Defence Services Admit Card",
        description: "Admit card for the Defence Services Exam 2024.",
        download_link:
          "https://example.com/download-defence-services-admit-card",
      },
      result: {
        title: "Defence Services Exam Results",
        description: "Results for the Defence Services Exam 2024.",
        results_link: "https://example.com/defence-services-results",
      },
    },
    {
      id: 12,
      heading: "Railway Recruitment Exam",
      post_date: "2024-12-10",
      total_vacancy: 220,
      brief_description: "An exam for recruitment into railway services.",
      adv_no: "RRE2024/12",
      application_fee_general: 550.0,
      application_fee_women: 275.0,
      application_fee_obc: 320.0,
      application_fee_st_sc: 220.0,
      starting_date_apply_online: "2025-01-01",
      last_date_apply: "2025-02-01",
      last_date_payment_fee: "2025-02-05",
      age_limit_minimum: 18,
      age_limit_maximum: 30,
      notification_link: "https://example.com/railway-recruitment-notify",
      apply_online_link: "https://example.com/railway-recruitment-apply",
      official_website_link: "https://example.com/railway-recruitment",
      admit_card: null,
      result: {
        title: "Railway Recruitment Exam Results",
        description: "Results for the Railway Recruitment Exam 2024.",
        results_link: "https://example.com/railway-recruitment-results",
      },
    },
    {
      id: 13,
      heading: "Banking Entrance Exam",
      post_date: "2025-01-10",
      total_vacancy: 160,
      brief_description: "An entrance exam for banking services.",
      adv_no: "BE2025/01",
      application_fee_general: 600.0,
      application_fee_women: 300.0,
      application_fee_obc: 350.0,
      application_fee_st_sc: 250.0,
      starting_date_apply_online: "2025-02-01",
      last_date_apply: "2025-03-01",
      last_date_payment_fee: "2025-03-05",
      age_limit_minimum: 21,
      age_limit_maximum: 29,
      notification_link: "https://example.com/banking-notify",
      apply_online_link: "https://example.com/banking-apply",
      official_website_link: "https://example.com/banking",
      admit_card: {
        title: "Banking Entrance Admit Card",
        description: "Admit card for the Banking Entrance Exam 2025.",
        download_link: "https://example.com/download-banking-admit-card",
      },
      result: null,
    },
    {
      id: 14,
      heading: "Insurance Exam",
      post_date: "2025-02-15",
      total_vacancy: 140,
      brief_description: "An exam for recruitment into insurance services.",
      adv_no: "IE2025/02",
      application_fee_general: 520.0,
      application_fee_women: 260.0,
      application_fee_obc: 310.0,
      application_fee_st_sc: 210.0,
      starting_date_apply_online: "2025-03-01",
      last_date_apply: "2025-04-01",
      last_date_payment_fee: "2025-04-05",
      age_limit_minimum: 18,
      age_limit_maximum: 28,
      notification_link: "https://example.com/insurance-notify",
      apply_online_link: "https://example.com/insurance-apply",
      official_website_link: "https://example.com/insurance",
      admit_card: null,
      result: {
        title: "Insurance Exam Results",
        description: "Results for the Insurance Exam 2025.",
        results_link: "https://example.com/insurance-results",
      },
    },
    {
      id: 15,
      heading: "Teaching Assistant Exam",
      post_date: "2025-03-05",
      total_vacancy: 100,
      brief_description: "An exam for the position of teaching assistants.",
      adv_no: "TA2025/03",
      application_fee_general: 470.0,
      application_fee_women: 235.0,
      application_fee_obc: 280.0,
      application_fee_st_sc: 190.0,
      starting_date_apply_online: "2025-04-01",
      last_date_apply: "2025-05-01",
      last_date_payment_fee: "2025-05-05",
      age_limit_minimum: 22,
      age_limit_maximum: 30,
      notification_link: "https://example.com/teaching-assistant-notify",
      apply_online_link: "https://example.com/teaching-assistant-apply",
      official_website_link: "https://example.com/teaching-assistant",
      admit_card: {
        title: "Teaching Assistant Exam Admit Card",
        description: "Admit card for the Teaching Assistant Exam 2025.",
        download_link:
          "https://example.com/download-teaching-assistant-admit-card",
      },
      result: {
        title: "Teaching Assistant Exam Results",
        description: "Results for the Teaching Assistant Exam 2025.",
        results_link: "https://example.com/teaching-assistant-results",
      },
    },
    {
      id: 16,
      heading: "Data Science Entrance Exam",
      post_date: "2025-04-10",
      total_vacancy: 80,
      brief_description: "An entrance exam for data science courses.",
      adv_no: "DSE2025/04",
      application_fee_general: 530.0,
      application_fee_women: 265.0,
      application_fee_obc: 315.0,
      application_fee_st_sc: 210.0,
      starting_date_apply_online: "2025-05-01",
      last_date_apply: "2025-06-01",
      last_date_payment_fee: "2025-06-05",
      age_limit_minimum: 20,
      age_limit_maximum: 30,
      notification_link: "https://example.com/data-science-notify",
      apply_online_link: "https://example.com/data-science-apply",
      official_website_link: "https://example.com/data-science",
      admit_card: null,
      result: {
        title: "Data Science Entrance Exam Results",
        description: "Results for the Data Science Entrance Exam 2025.",
        results_link: "https://example.com/data-science-results",
      },
    },
    {
      id: 17,
      heading: "Software Engineering Exam",
      post_date: "2025-05-15",
      total_vacancy: 120,
      brief_description: "An exam for software engineering courses.",
      adv_no: "SE2025/05",
      application_fee_general: 560.0,
      application_fee_women: 280.0,
      application_fee_obc: 325.0,
      application_fee_st_sc: 220.0,
      starting_date_apply_online: "2025-06-01",
      last_date_apply: "2025-07-01",
      last_date_payment_fee: "2025-07-05",
      age_limit_minimum: 18,
      age_limit_maximum: 27,
      notification_link: "https://example.com/software-engineering-notify",
      apply_online_link: "https://example.com/software-engineering-apply",
      official_website_link: "https://example.com/software-engineering",
      admit_card: {
        title: "Software Engineering Exam Admit Card",
        description: "Admit card for the Software Engineering Exam 2025.",
        download_link:
          "https://example.com/download-software-engineering-admit-card",
      },
      result: null,
    },
    {
      id: 18,
      heading: "Artificial Intelligence Exam",
      post_date: "2025-06-10",
      total_vacancy: 70,
      brief_description: "An exam for artificial intelligence courses.",
      adv_no: "AI2025/06",
      application_fee_general: 580.0,
      application_fee_women: 290.0,
      application_fee_obc: 340.0,
      application_fee_st_sc: 230.0,
      starting_date_apply_online: "2025-07-01",
      last_date_apply: "2025-08-01",
      last_date_payment_fee: "2025-08-05",
      age_limit_minimum: 22,
      age_limit_maximum: 29,
      notification_link: "https://example.com/ai-notify",
      apply_online_link: "https://example.com/ai-apply",
      official_website_link: "https://example.com/ai",
      admit_card: null,
      result: {
        title: "Artificial Intelligence Exam Results",
        description: "Results for the Artificial Intelligence Exam 2025.",
        results_link: "https://example.com/ai-results",
      },
    },
    {
      id: 19,
      heading: "Cybersecurity Exam",
      post_date: "2025-07-20",
      total_vacancy: 100,
      brief_description: "An exam for cybersecurity courses.",
      adv_no: "CE2025/07",
      application_fee_general: 600.0,
      application_fee_women: 300.0,
      application_fee_obc: 350.0,
      application_fee_st_sc: 250.0,
      starting_date_apply_online: "2025-08-01",
      last_date_apply: "2025-09-01",
      last_date_payment_fee: "2025-09-05",
      age_limit_minimum: 18,
      age_limit_maximum: 30,
      notification_link: "https://example.com/cybersecurity-notify",
      apply_online_link: "https://example.com/cybersecurity-apply",
      official_website_link: "https://example.com/cybersecurity",
      admit_card: {
        title: "Cybersecurity Exam Admit Card",
        description: "Admit card for the Cybersecurity Exam 2025.",
        download_link: "https://example.com/download-cybersecurity-admit-card",
      },
      result: null,
    },
    {
      id: 20,
      heading: "Data Analysis Exam",
      post_date: "2025-08-25",
      total_vacancy: 90,
      brief_description: "An exam for data analysis courses.",
      adv_no: "DA2025/08",
      application_fee_general: 500.0,
      application_fee_women: 250.0,
      application_fee_obc: 300.0,
      application_fee_st_sc: 200.0,
      starting_date_apply_online: "2025-09-01",
      last_date_apply: "2025-10-01",
      last_date_payment_fee: "2025-10-05",
      age_limit_minimum: 21,
      age_limit_maximum: 30,
      notification_link: "https://example.com/data-analysis-notify",
      apply_online_link: "https://example.com/data-analysis-apply",
      official_website_link: "https://example.com/data-analysis",
      admit_card: {
        title: "Data Analysis Exam Admit Card",
        description: "Admit card for the Data Analysis Exam 2025.",
        download_link: "https://example.com/download-data-analysis-admit-card",
      },
      result: {
        title: "Data Analysis Exam Results",
        description: "Results for the Data Analysis Exam 2025.",
        results_link: "https://example.com/data-analysis-results",
      },
    },
    {
      id: 21,
      heading: "Computer Science Exam",
      post_date: "2025-09-15",
      total_vacancy: 110,
      brief_description: "An exam for computer science courses.",
      adv_no: "CS2025/09",
      application_fee_general: 570.0,
      application_fee_women: 285.0,
      application_fee_obc: 320.0,
      application_fee_st_sc: 225.0,
      starting_date_apply_online: "2025-10-01",
      last_date_apply: "2025-11-01",
      last_date_payment_fee: "2025-11-05",
      age_limit_minimum: 18,
      age_limit_maximum: 27,
      notification_link: "https://example.com/computer-science-notify",
      apply_online_link: "https://example.com/computer-science-apply",
      official_website_link: "https://example.com/computer-science",
      admit_card: null,
      result: {
        title: "Computer Science Exam Results",
        description: "Results for the Computer Science Exam 2025.",
        results_link: "https://example.com/computer-science-results",
      },
    },
    {
      id: 22,
      heading: "Cloud Computing Exam",
      post_date: "2025-10-20",
      total_vacancy: 95,
      brief_description: "An exam for cloud computing courses.",
      adv_no: "CC2025/10",
      application_fee_general: 550.0,
      application_fee_women: 275.0,
      application_fee_obc: 320.0,
      application_fee_st_sc: 220.0,
      starting_date_apply_online: "2025-11-01",
      last_date_apply: "2025-12-01",
      last_date_payment_fee: "2025-12-05",
      age_limit_minimum: 20,
      age_limit_maximum: 28,
      notification_link: "https://example.com/cloud-computing-notify",
      apply_online_link: "https://example.com/cloud-computing-apply",
      official_website_link: "https://example.com/cloud-computing",
      admit_card: null,
      result: {
        title: "Cloud Computing Exam Results",
        description: "Results for the Cloud Computing Exam 2025.",
        results_link: "https://example.com/cloud-computing-results",
      },
    },
    {
      id: 23,
      heading: "Robotics Exam",
      post_date: "2025-11-05",
      total_vacancy: 85,
      brief_description: "An exam for robotics courses.",
      adv_no: "RE2025/11",
      application_fee_general: 540.0,
      application_fee_women: 270.0,
      application_fee_obc: 310.0,
      application_fee_st_sc: 200.0,
      starting_date_apply_online: "2025-12-01",
      last_date_apply: "2026-01-01",
      last_date_payment_fee: "2026-01-05",
      age_limit_minimum: 22,
      age_limit_maximum: 30,
      notification_link: "https://example.com/robotics-notify",
      apply_online_link: "https://example.com/robotics-apply",
      official_website_link: "https://example.com/robotics",
      admit_card: {
        title: "Robotics Exam Admit Card",
        description: "Admit card for the Robotics Exam 2025.",
        download_link: "https://example.com/download-robotics-admit-card",
      },
      result: {
        title: "Robotics Exam Results",
        description: "Results for the Robotics Exam 2025.",
        results_link: "https://example.com/robotics-results",
      },
    },
  ],
};

export default dummyData;
